name = "travelog"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "travelog"
database_id = "f524c539-d7b6-479b-aab3-ae1361dddd35"
